### ISSUE TITLE
HTML or PDF instructions

### ISSUE THREAD

**Issue by ghost** [pnprog/grp-documentation#2]
Please commit HTML/PDF creation instructions. I'm using ReText now and it doesn't build internal links, which I'd like to test as I'm translating.

**Comment by pnprog** [comment]
I use Pandoc for the conversion.

Something like:

`pandoc -s --toc documentation_en.md -o doc.htm`

**Comment by ghost** [comment]
Thanks. I expanded this command and opened a new pull request, but GitHub squashes the new pull request commits into the already open one if there is any. I'd don't know how to avoid this.

#3

**Comment by ghost** [comment]
I think the reason is the repository setting in this image:

![merge_squash](https://user-images.githubusercontent.com/12538058/54189131-72f3ef00-44b1-11e9-80c5-463cf9c347d2.png)
